INSERT INTO tips (title, category, problem, solution, author_result, warning, tags, votes_up, votes_down, hidden) VALUES
('Vodní kámen na baterii', 'Úklid & čištění', 'Na baterii je silná vrstva vodního kamene.', 'Obal baterii hadrem namočeným v octu a nech 30 minut působit, pak setři.', 'fungovalo', 'Nepoužívat na matné nebo lakované povrchy.', ARRAY['vodní kámen','ocet','koupelna'], 1, 0, false),
('Mastnota na digestoři', 'Úklid & čištění', 'Digestoř je pokrytá mastnotou.', 'Použij horkou vodu s jarem a hadr, poté opláchni čistou vodou.', 'fungovalo', NULL, ARRAY['mastnota','kuchyně','čištění'], 1, 0, false),
('Zápach z pračky', 'Prádlo & textil', 'Pračka zapáchá po praní.', 'Spusť prázdný cyklus na 60°C s hrnkem octa.', 'fungovalo', NULL, ARRAY['zápach','pračka','ocet'], 1, 0, false),
('Skvrny od vína', 'Prádlo & textil', 'Na tričku je skvrna od červeného vína.', 'Posyp skvrnu solí a poté vyper.', 'nefungovalo', 'Může skvrnu zafixovat.', ARRAY['skvrny','víno','prádlo'], 0, 1, false),
('Připálená pánev', 'Kuchyně & vaření', 'Na pánvi je připálené jídlo.', 'Nalij vodu, přidej jedlou sodu a nech krátce povařit.', 'fungovalo', NULL, ARRAY['připálené','soda','kuchyně'], 1, 0, false),
('Zápach z lednice', 'Kuchyně & vaření', 'Lednice nepříjemně zapáchá.', 'Dej dovnitř misku s jedlou sodou.', 'fungovalo', NULL, ARRAY['zápach','lednice','soda'], 1, 0, false),
('Plíseň v koupelně', 'Koupelna & hygiena', 'Na spárách je plíseň.', 'Použij ocet nebo speciální přípravek a kartáček.', 'fungovalo', NULL, ARRAY['plíseň','koupelna','čištění'], 1, 0, false),
('Chlupy na gauči', 'Zvířata v domácnosti', 'Na gauči jsou chlupy od psa.', 'Použij vlhký gumový rukavice a setři.', 'fungovalo', NULL, ARRAY['chlupy','pes','gauč'], 1, 0, false),
('Zápach z bot', 'Domácí vychytávky', 'Boty zapáchají.', 'Nasyp do nich jedlou sodu přes noc.', 'fungovalo', NULL, ARRAY['zápach','boty','soda'], 1, 0, false),
('Šmouhy na skle', 'Úklid & čištění', 'Na oknech zůstávají šmouhy.', 'Použij noviny místo hadru.', 'nefungovalo', 'Může zanechat inkoust.', ARRAY['sklo','okna','čištění'], 0, 1, false),
('Ucpaný odpad', 'Koupelna & hygiena', 'Odpad odtéká pomalu.', 'Nasyp sodu, zalij octem a spláchni horkou vodou.', 'fungovalo', NULL, ARRAY['odpad','soda','ocet'], 1, 0, false),
('Tvrdé ručníky', 'Prádlo & textil', 'Ručníky jsou tvrdé.', 'Přidej ocet místo aviváže.', 'fungovalo', NULL, ARRAY['prádlo','ocet','ručníky'], 1, 0, false),
('Skvrny na koberci', 'Úklid & čištění', 'Na koberci je skvrna.', 'Použij směs vody a jaru.', 'fungovalo', NULL, ARRAY['koberec','skvrny','čištění'], 1, 0, false),
('Přeschlá rostlina', 'Zahrada & balkon', 'Rostlina vadne.', 'Důkladně zalij a nech okapat.', 'fungovalo', NULL, ARRAY['rostliny','zalévání','balkon'], 1, 0, false),
('Zatuchlý pelíšek', 'Zvířata v domácnosti', 'Pelíšek psa zapáchá.', 'Vyprat na vyšší teplotu s octem.', 'fungovalo', NULL, ARRAY['pes','pelíšek','zápach'], 1, 0, false),
('Připálená trouba', 'Kuchyně & vaření', 'Trouba je špinavá od připálenin.', 'Použij pastu z jedlé sody a vody, nech působit.', 'fungovalo', NULL, ARRAY['trouba','soda','čištění'], 1, 0, false),
('Lepení papíru', 'Tvoření & DIY', 'Papír se špatně lepí.', 'Použij lepidlo v tyčince místo tekutého.', 'fungovalo', NULL, ARRAY['lepení','DIY','papír'], 1, 0, false),
('Organizace kabelů', 'Domácnost & organizace', 'Kabely jsou zamotané.', 'Použij gumičky nebo krabičky.', 'fungovalo', NULL, ARRAY['kabely','organizace','domácnost'], 1, 0, false),
('Skvrny od trávy', 'Prádlo & textil', 'Na oblečení jsou skvrny od trávy.', 'Použij alkohol nebo speciální odstraňovač.', 'fungovalo', NULL, ARRAY['skvrny','tráva','prádlo'], 1, 0, false),
('Špinavé spáry', 'Koupelna & hygiena', 'Spáry jsou špinavé.', 'Použij kartáček a čisticí prostředek.', 'fungovalo', NULL, ARRAY['spáry','koupelna','čištění'], 1, 0, false),
('Zápach z odpadkového koše', 'Domácí vychytávky', 'Koš zapáchá.', 'Dej na dno jedlou sodu.', 'fungovalo', NULL, ARRAY['zápach','koš','soda'], 1, 0, false),
('Rozbitý zip', 'Kutilství', 'Zip se zasekává.', 'Potři ho voskem nebo mýdlem.', 'fungovalo', NULL, ARRAY['zip','oprava','oblečení'], 1, 0, false),
('Zaschlá mastnota', 'Úklid & čištění', 'Na povrchu je stará mastnota.', 'Použij teplou vodu a odmašťovač.', 'fungovalo', NULL, ARRAY['mastnota','čištění','kuchyně'], 1, 0, false),
('Ztvrdlá houbička', 'Domácí vychytávky', 'Houbička je tvrdá a zapáchá.', 'Dej ji do mikrovlnky na pár sekund.', 'nefungovalo', 'Může se poškodit.', ARRAY['houbička','kuchyně','zápach'], 0, 1, false),
('Poškrábaný nábytek', 'Kutilství', 'Na nábytku jsou drobné škrábance.', 'Použij olej nebo vosk.', 'fungovalo', NULL, ARRAY['nábytek','oprava','škrábance'], 1, 0, false),
('Zapařené oblečení', 'Prádlo & textil', 'Oblečení zapáchá po praní.', 'Zkus znovu vyprat s octem.', 'fungovalo', NULL, ARRAY['zápach','prádlo','ocet'], 1, 0, false),
('Plevel na balkoně', 'Zahrada & balkon', 'Mezi dlaždicemi roste plevel.', 'Vytrhej ručně nebo použij horkou vodu.', 'fungovalo', NULL, ARRAY['plevel','balkon','zahrada'], 1, 0, false),
('Zbytky lepidla', 'Úklid & čištění', 'Na povrchu zůstalo lepidlo.', 'Použij olej nebo alkohol.', 'fungovalo', NULL, ARRAY['lepidlo','čištění','povrch'], 1, 0, false),
('Zaseklé dveře', 'Kutilství', 'Dveře vržou nebo drhnou.', 'Použij olej na panty.', 'fungovalo', NULL, ARRAY['dveře','oprava','mazání'], 1, 0, false),
('Zbytky vosku', 'Úklid & čištění', 'Na stole je vosk ze svíčky.', 'Nech ztuhnout a pak seškrábni.', 'fungovalo', NULL, ARRAY['vosk','čištění','stůl'], 1, 0, false);
