import { Tip } from "./types";

export const MOCK_TIPS: Tip[] = [
  {
    id: "1",
    title: "Ocet na vodní kámen v konvici",
    category: "Kuchyně & vaření",
    problem: "Vodní kámen uvnitř konvice, voda začíná divně chutnat.",
    solution:
      "Naplň konvici směsí 1:1 voda + bílý ocet, přiveď k varu, nech 1 hodinu stát, vylij a proplachni čistou vodou. Zopakuj jednou čistou vodou.",
    authorResult: "fungovalo",
    warning: "Po proplachnutí opři konvici víčkem, aby pach octu dobře vytrál.",
    tags: ["vodní kámen", "ocet", "kuchyně"],
    votes_up: 84,
    votes_down: 9,
    createdAt: "2024-11-01",
  },
  {
    id: "2",
    title: "Jedlá soda na zápach v lednici",
    category: "Kuchyně & vaření",
    problem: "Lednice táhne nepříjemným zápachem i po vyčištění.",
    solution:
      "Dej do lednice otevřenou misku s jedlou sodou. Nech působit 24–48 hodin. Soda absorbuje zápach.",
    authorResult: "fungovalo",
    tags: ["zápach", "jedlá soda", "kuchyně", "přírodní"],
    votes_up: 71,
    votes_down: 8,
    createdAt: "2024-11-05",
  },
  {
    id: "3",
    title: "Citron na skvrny od kávy v hrncích",
    category: "Kuchyně & vaření",
    problem: "Hnědé skvrny od čaje a kávy uvnitř hrnků, nejdou umýt.",
    solution:
      "Namočte hrnek solí, pak vetřete půlku citronu. Nechte 5 minut, opláchněte.",
    authorResult: "fungovalo",
    tags: ["skvrny", "citron", "kuchyně", "přírodní"],
    votes_up: 55,
    votes_down: 14,
    createdAt: "2024-11-10",
  },
  {
    id: "4",
    title: "Ocet na plíseň v koupelně",
    category: "Koupelna & hygiena",
    problem: "Plíseň ve spárách dlaždic a kolem vany.",
    solution:
      "Nastříkej čistý bílý ocet na postižená místa, nech 1 hodinu, vydrhni starým zubním kartáčkem.",
    authorResult: "fungovalo",
    warning:
      "Nepřidávej chlorové čisticí prostředky — kombinace s octem uvolňuje nebezpečné výpary.",
    tags: ["plíseň", "ocet", "koupelna"],
    votes_up: 38,
    votes_down: 27,
    createdAt: "2024-11-12",
  },
  {
    id: "5",
    title: "Jedlá soda + ocet na ucpaný odtok",
    category: "Koupelna & hygiena",
    problem: "Pomalý odtok ve sprše, voda stojí a nechce odtékat.",
    solution:
      "Sypni 3 lžíce jedlé sody do odtoku, pak přidej hrnek octa. Nech 15 minut bouřit, pak spláchni vroucí vodou.",
    authorResult: "nefungovalo",
    warning:
      "Při silném ucpání nepomůže — v takovém případě je nutný mechanický čistič nebo instalatér.",
    tags: ["zápach", "jedlá soda", "ocet", "koupelna"],
    votes_up: 12,
    votes_down: 41,
    createdAt: "2024-11-15",
  },
  {
    id: "6",
    title: "Mražení na likvidaci roztočů v polštářích",
    category: "Prádlo & textil",
    problem: "Alergik v domácnosti, podezření na roztoče v polštářích.",
    solution:
      "Vlož polštář do plastového sáčku, dej na 48 hodin do mrazáku (-18 °C). Pak vynes ven, vysus.",
    authorResult: "fungovalo",
    tags: ["přírodní"],
    votes_up: 29,
    votes_down: 19,
    createdAt: "2024-11-18",
  },
  {
    id: "7",
    title: "Žluč na tukové skvrny z oblečení",
    category: "Prádlo & textil",
    problem: "Mastná skvrna od jídla na tričku, nepomáhá ani předpírání.",
    solution:
      "Nanes žlučové mýdlo přímo na skvrnu (vlhkou), jemně vetři, nech 30 minut působit, pak standardně vyper.",
    authorResult: "fungovalo",
    tags: ["mastnota", "skvrny"],
    votes_up: 67,
    votes_down: 7,
    createdAt: "2024-11-20",
  },
  {
    id: "8",
    title: "Ocet v pračce na zápach prádla",
    category: "Prádlo & textil",
    problem: "Prádlo smrdí i po vyprání, zvláště ručníky.",
    solution:
      "Přidej 100 ml bílého octa do aviváž přihrádky místo aviváže. Ber to jako reset pračky — zopakuj 2–3 praní.",
    authorResult: "fungovalo",
    tags: ["zápach", "ocet", "pračka", "přírodní"],
    votes_up: 48,
    votes_down: 22,
    createdAt: "2024-11-22",
  },
  {
    id: "9",
    title: "Sůl na čerstvou skvrnu od červeného vína",
    category: "Úklid & čištění",
    problem: "Červené víno na koberci nebo ubrus, právě se stalo.",
    solution:
      "Okamžitě nasypte velké množství soli na skvrnu, nechte absorbovat 10 minut (sůl zčervená). Vysaj nebo setřes.",
    authorResult: "fungovalo",
    warning: "Funguje jen čerstvá skvrna — na zaschlé víno tohle nestačí.",
    tags: ["skvrny", "přírodní"],
    votes_up: 73,
    votes_down: 8,
    createdAt: "2024-11-25",
  },
  {
    id: "10",
    title: "Kávová sedlina jako hnojivo pro pokojovky",
    category: "Zahrada & balkon",
    problem: "Pokojové rostliny žloutnoucí, hledám levné hnojivo.",
    solution:
      "Po uvaření kávy nech sedlinu vychladnout, zamíchej do zeminy (ne příliš mnoho — jen tenká vrstva). Opakuj 1× za 2 týdny.",
    authorResult: "fungovalo",
    warning:
      "Kávová sedlina okyseluje půdu — nevhodná pro rostliny preferující zásaditou půdu (kaktusy, sukulenty).",
    tags: ["přírodní"],
    votes_up: 41,
    votes_down: 31,
    createdAt: "2024-11-27",
  },
  {
    id: "11",
    title: "Citronová kůra v mikrovlnce",
    category: "Kuchyně & vaření",
    problem: "Mikrovlnka páchne starým jídlem, nejde to vydřít.",
    solution:
      "Dej do misky s vodou citronovou kůru nebo pár kapek citronové šťávy. Zahřívej 3 minuty na max. výkon. Nech 2 min. stát, pak otři vlhkým hadříkem.",
    authorResult: "fungovalo",
    tags: ["zápach", "citron", "kuchyně", "přírodní"],
    votes_up: 79,
    votes_down: 4,
    createdAt: "2024-12-01",
  },
  {
    id: "12",
    title: "Pasta na zuby na drobná škrábání na obrazovce",
    category: "Domácí vychytávky",
    problem: "Drobné škrábance na displeji telefonu nebo notebooku.",
    solution:
      "Nanes malé množství bílé pasty na zuby na mikrohadřík, jemně kroužkovými pohyby vetři do škrábance 1–2 minuty. Otři čistým hadříkem.",
    authorResult: "nefungovalo",
    warning:
      "Může poškodit povrchové antireflexní vrstvy — riziko je větší než zisk. Nedoporučuji.",
    tags: ["chemie"],
    votes_up: 6,
    votes_down: 28,
    createdAt: "2024-12-03",
  },
];
